#!/bin/bash
BUILD_DIR="build"

CLEAN=false
TEST=false
while [[ $# -gt 0 ]]; do
  case $1 in
    clean) CLEAN=true; shift ;;
    test) TEST=true; shift ;;
    *) echo "Unknown option [$1]"; exit ;;
  esac
done

if $CLEAN; then rm -rf "$BUILD_DIR"; fi

if [ ! -d "$BUILD_DIR" ]; then mkdir "$BUILD_DIR"; fi
cd "$BUILD_DIR"
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
if [ "$?" -ne 0 ]; then exit; fi

if $TEST; then ./tests; fi