#!/bin/bash
BUILD_DIR="build"
export SOURCE_FILES="$(find src -name '*.[hc]pp' | tr '\n' ';')"

CLEAN=false
TEST=false
while [[ $# -gt 0 ]]; do
  case $1 in
    clean) CLEAN=true; shift ;;
    test) TEST=true; shift ;;
    *) echo "Unknown option [$1]"; exit ;;
  esac
done

if $CLEAN; then rm -rf "$BUILD_DIR"; fi

if [ ! -d "$BUILD_DIR" ]; then mkdir "$BUILD_DIR"; fi
cd "$BUILD_DIR"
cmake -DCMAKE_BUILD_TYPE=Debug ..
make

if $TEST; then ctest; fi